# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'solution' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for solution

  # Asynchronus loading images
  pod 'Kingfisher', :git => "https://github.com/onevcat/Kingfisher.git", :tag => "5.2.0"
end
